apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: cr5lle47l-go 
  janus-idp.io/tekton: cr5lle47l-go
  backstage.io/kubernetes-id: cr5lle47l-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: cr5lle47l-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml