apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: cr5lle47l-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cr5lle47l-go 
  name: cr5lle47l-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: cr5lle47l-go 
